// <auto-generated />
using Mango.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220816151738_SeedProducts")]
    partial class SeedProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ImageUrl = "https://res.cloudinary.com/dyej4hpgt/image/upload/v1646843779/heroes/marvel-wolverine.jpg",
                            ProductCategoryName = "Entree",
                            ProductDescription = "Fry chicken Dominican style",
                            ProductName = "PolloPica",
                            ProductPrice = 12.0
                        },
                        new
                        {
                            ProductId = 2,
                            ImageUrl = "https://res.cloudinary.com/dyej4hpgt/image/upload/v1646843779/heroes/marvel-thor.jpg",
                            ProductCategoryName = "Appetizer",
                            ProductDescription = "Mango Dominican style",
                            ProductName = "MangoChimi",
                            ProductPrice = 6.0
                        },
                        new
                        {
                            ProductId = 3,
                            ImageUrl = "https://res.cloudinary.com/dyej4hpgt/image/upload/v1646843778/heroes/marvel-spider.jpg",
                            ProductCategoryName = "Appetizer",
                            ProductDescription = "Mango shake Dominican style",
                            ProductName = "Mango Shake",
                            ProductPrice = 5.0
                        },
                        new
                        {
                            ProductId = 4,
                            ImageUrl = "https://res.cloudinary.com/dyej4hpgt/image/upload/v1646843777/heroes/marvel-iron.jpg",
                            ProductCategoryName = "Appetizer",
                            ProductDescription = "Mixed Fruits",
                            ProductName = "Mango & friends",
                            ProductPrice = 12.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
